'------------------------------------------------------------------------------
' <auto-generated>
'     This code was generated by a tool.
'     Runtime Version:4.0.30319.18444
'
'     Changes to this file may cause incorrect behavior and will be lost if
'     the code is regenerated.
' </auto-generated>
'------------------------------------------------------------------------------

Option Strict On
Option Explicit On

Imports System

Namespace My.Resources
    
    'This class was auto-generated by the StronglyTypedResourceBuilder
    'class via a tool like ResGen or Visual Studio.
    'To add or remove a member, edit your .ResX file then rerun ResGen
    'with the /str option, or rebuild your VS project.
    '''<summary>
    '''  A strongly-typed resource class, for looking up localized strings, etc.
    '''</summary>
    <Global.System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "4.0.0.0"),  _
     Global.System.Diagnostics.DebuggerNonUserCodeAttribute(),  _
     Global.System.Runtime.CompilerServices.CompilerGeneratedAttribute(),  _
     Global.Microsoft.VisualBasic.HideModuleNameAttribute()>  _
    Friend Module Resources
        
        Private resourceMan As Global.System.Resources.ResourceManager
        
        Private resourceCulture As Global.System.Globalization.CultureInfo
        
        '''<summary>
        '''  Returns the cached ResourceManager instance used by this class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend ReadOnly Property ResourceManager() As Global.System.Resources.ResourceManager
            Get
                If Object.ReferenceEquals(resourceMan, Nothing) Then
                    Dim temp As Global.System.Resources.ResourceManager = New Global.System.Resources.ResourceManager("OL3Designer.Resources", GetType(Resources).Assembly)
                    resourceMan = temp
                End If
                Return resourceMan
            End Get
        End Property
        
        '''<summary>
        '''  Overrides the current thread's CurrentUICulture property for all
        '''  resource lookups using this strongly typed resource class.
        '''</summary>
        <Global.System.ComponentModel.EditorBrowsableAttribute(Global.System.ComponentModel.EditorBrowsableState.Advanced)>  _
        Friend Property Culture() As Global.System.Globalization.CultureInfo
            Get
                Return resourceCulture
            End Get
            Set
                resourceCulture = value
            End Set
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to // Copyright 2006 The Closure Library Authors. All Rights Reserved.
        '''//
        '''// Licensed under the Apache License, Version 2.0 (the &quot;License&quot;);
        '''// you may not use this file except in compliance with the License.
        '''// You may obtain a copy of the License at
        '''//
        '''//      http://www.apache.org/licenses/LICENSE-2.0
        '''//
        '''// Unless required by applicable law or agreed to in writing, software
        '''// distributed under the License is distributed on an &quot;AS-IS&quot; BASIS,
        '''// WITHOUT WARRANTIES OR CONDITIONS OF ANY KIND, either express or [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property base() As String
            Get
                Return ResourceManager.GetString("base", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to /*!
        ''' * Bootstrap v2.3.1
        ''' *
        ''' * Copyright 2012 Twitter, Inc
        ''' * Licensed under the Apache License v2.0
        ''' * http://www.apache.org/licenses/LICENSE-2.0
        ''' *
        ''' * Designed and built with all the love in the world @twitter by @mdo and @fat.
        ''' */
        '''
        '''.clearfix {
        '''  *zoom: 1;
        '''}
        '''
        '''.clearfix:before,
        '''.clearfix:after {
        '''  display: table;
        '''  line-height: 0;
        '''  content: &quot;&quot;;
        '''}
        '''
        '''.clearfix:after {
        '''  clear: both;
        '''}
        '''
        '''.hide-text {
        '''  font: 0/0 a;
        '''  color: transparent;
        '''  text-shadow: none;
        '''  background-color: transparent;
        '''  border: 0;
        '''}
        '''
        '''.inpu [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property bootstrap() As String
            Get
                Return ResourceManager.GetString("bootstrap", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to /*!
        '''* Bootstrap.js by @fat &amp; @mdo
        '''* Copyright 2012 Twitter, Inc.
        '''* http://www.apache.org/licenses/LICENSE-2.0.txt
        '''*/
        '''!function(e){&quot;use strict&quot;;e(function(){e.support.transition=function(){var e=function(){var e=document.createElement(&quot;bootstrap&quot;),t={WebkitTransition:&quot;webkitTransitionEnd&quot;,MozTransition:&quot;transitionend&quot;,OTransition:&quot;oTransitionEnd otransitionend&quot;,transition:&quot;transitionend&quot;},n;for(n in t)if(e.style[n]!==undefined)return t[n]}();return e&amp;&amp;{end:e}}()})}(window.jQuery),!function(e){&quot;use stric [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property bootstrap1() As String
            Get
                Return ResourceManager.GetString("bootstrap1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to 0,255,255|0,255,0|255,255,0|255,0,0
        '''255,40,50|50,255,10
        '''200,90,255|25,255,50
        '''10,68,230|47,10,5|230,250,10|40,40,80
        '''205,250,150|120,180,75
        '''130,140,150|240,50,200
        '''100,200,40|56,77,200.
        '''</summary>
        Friend ReadOnly Property colourRamps() As String
            Get
                Return ResourceManager.GetString("colourRamps", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property column_16xLG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("column_16xLG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property column_16xLG___Copy() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("column_16xLG___Copy", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to Direction Marker:1,0,bottom-left,0.5,fraction,0.5,fraction;
        '''Green Flat Headed Pin:1,0,bottom-left,0.5,fraction,0.5,fraction;
        '''Green Marker:1,0,bottom-left,0.5,fraction,0.5,fraction;
        '''Black Marker:1,0,bottom-left,0.5,fraction,0.5,fraction;
        '''Blue Dot:1,0,bottom-left,0.5,fraction,0.5,fraction;
        '''Green Pin:1,0,bottom-left,0.5,fraction,0.5,fraction;
        '''Orange Pin:1,0,bottom-left,0.5,fraction,0.5,fraction;
        '''Straight Blue Pin:1,0,bottom-left,0.5,fraction,0.5,fraction;
        '''Blue Dashed:2,#0000FF,round,round,0,4;
        '''Red Lin [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property DefaultStyleSettings() As String
            Get
                Return ResourceManager.GetString("DefaultStyleSettings", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property dialog_16xLG() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("dialog_16xLG", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Editdatasetwithdesigner_8449() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Editdatasetwithdesigner_8449", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to //only add once , not with every map
        '''
        '''function setMaxExtent(theMap){
        '''var hasVectorLayer = 0;
        '''//get map view
        '''var view = theMap.getView();
        '''//set up blank extent
        '''var theExtent = new ol.extent.createEmpty();
        '''
        '''//cycle through layers
        '''for (i = 0; i &lt; theMap.getLayers().getLength(); i++) { 
        '''if (theMap.getLayers().item(i) instanceof ol.layer.Tile ){}else{
        '''if (hasVectorLayer != 1){
        '''theExtent = theMap.getLayers().item(i).getSource().getExtent();
        '''}
        '''//alert(theMap.getLayers().item(i).get(&apos;name&apos;));
        '''hasVec [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property extentFunction() As String
            Get
                Return ResourceManager.GetString("extentFunction", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!doctype html&gt;
        '''&lt;html lang=&quot;en&quot;  style=&apos;margin:0;padding:0;width: 100%; height: 100%;overflow:hidden;&apos;&gt;
        '''  &lt;head&gt;
        '''    &lt;meta charset=&quot;utf-8&quot;&gt;
        '''	&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;/&gt;
        '''
        '''  &lt;/head&gt;
        '''  
        '''	&lt;body  style=&apos;margin:0;padding:0;width: 100%; height: 100%;&apos;&gt;
        '''&lt;script src=&apos;OLFILEPATHol.js&apos; type=&apos;text/javascript&apos;&gt;&lt;/script&gt; &lt;link rel=&apos;stylesheet&apos; href=&apos;ol.css&apos; type=&apos;text/css&apos;&gt;
        '''&lt;script src=&apos;OLFILEPATHproj4.js&apos; type=&apos;text/javascript&apos;&gt;&lt;/script&gt; 
        '''
        '''
        '''&lt;script src=&apos;OLFILEPATHbase.js&apos; type=&apos;text/jav [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property HeatmapPreview() As String
            Get
                Return ResourceManager.GetString("HeatmapPreview", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to /*! jQuery v1.7.2 jquery.com | jquery.org/license */
        '''(function(a,b){function cy(a){return f.isWindow(a)?a:a.nodeType===9?a.defaultView||a.parentWindow:!1}function cu(a){if(!cj[a]){var b=c.body,d=f(&quot;&lt;&quot;+a+&quot;&gt;&quot;).appendTo(b),e=d.css(&quot;display&quot;);d.remove();if(e===&quot;none&quot;||e===&quot;&quot;){ck||(ck=c.createElement(&quot;iframe&quot;),ck.frameBorder=ck.width=ck.height=0),b.appendChild(ck);if(!cl||!ck.createElement)cl=(ck.contentWindow||ck.contentDocument).document,cl.write((f.support.boxModel?&quot;&lt;!doctype html&gt;&quot;:&quot;&quot;)+&quot;&lt;html&gt;&lt;body&gt;&quot;),cl.cl [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property jQuery() As String
            Get
                Return ResourceManager.GetString("jQuery", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to function createKey(keyObject){
        '''var changeHandlerEvals = &quot;&quot;;
        '''keyLayers = keyObject[&apos;keyLayers&apos;];
        '''keyDiv = keyObject[&apos;keyDiv&apos;];
        '''keyHeading = keyObject[&apos;keyTitle&apos;];
        '''keyPadding = keyObject[&apos;keyPadding&apos;];
        '''keyPatchSize = keyObject[&apos;keyPatchSize&apos;];
        '''
        '''//blank anything in div
        '''document.getElementById(keyDiv).innerHTML = &quot;&quot;;
        '''
        '''//get info
        '''var numberOfKeyLayers = keyLayers.length;
        '''var theKeyHTML = &quot;&lt;div  style=&apos;padding:&quot; + keyPadding + &quot;px;&apos;&gt;&quot; + keyHeading;
        '''
        '''//for each layer you need 1. the styles . 2. the values which re [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property keyFunction() As String
            Get
                Return ResourceManager.GetString("keyFunction", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!doctype html&gt;
        '''&lt;html lang=&quot;en&quot;  style=&apos;margin:0;padding:0;width: 100%; height: 100%;overflow:hidden;&apos;&gt;
        '''  &lt;head&gt;
        '''    &lt;meta charset=&quot;utf-8&quot;&gt;
        '''	&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;/&gt;
        '''
        '''  &lt;/head&gt;
        '''  
        '''	&lt;body  style=&apos;margin:0;padding:0;width: 100%; height: 100%;&apos;&gt;
        '''		&lt;div id=&quot;map&quot; style=&quot;width: 100%; height: 100%;margin:0;padding:0;&quot;&gt;&lt;/div&gt;
        '''		&lt;script src=&quot;OLFILEPATHol.js&quot; type=&quot;text/javascript&quot;&gt;&lt;/script&gt;
        '''	
        '''&lt;script&gt;
        '''
        '''var PointFeature = new ol.Feature({
        '''  geometry: new ol.geom.Point([0,  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property LABELJS() As String
            Get
                Return ResourceManager.GetString("LABELJS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property Offline_16xLG__2() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("Offline_16xLG__2", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .ol-attribution{position:absolute;text-align:right;bottom:0;right:0;padding:6px;color:#000;color:rgba(238,238,238,1);background:rgba(0,60,136,0.3)}.ol-attribution a{text-decoration:none;color:#7b98bc;color:rgba(255,255,255,1)}.ol-attribution ul{margin:0;padding:0;font-size:10px;line-height:12px}.ol-attribution li{display:inline;list-style:none;line-height:inherit}.ol-attribution li:not(:last-child):after{content:&quot;\002003&quot;}.ol-attribution-bing-tos{float:right;padding-top:2px;white-space:nowrap}.ol-logo{botto [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property ol() As String
            Get
                Return ResourceManager.GetString("ol", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to // This file was autogenerated by /home/elemoine/src/openlayers.github.io/.grunt/openlayers-website/repo/node_modules/closure-util/.deps/library/8ef01183c539886a0c0458d8cc6d968170ae8d76/closure/bin/build/depswriter.py.
        '''// Please do not edit.
        '''goog.addDependency(&apos;../../../ol/ol/animation.js&apos;, [&apos;ol.animation&apos;], [&apos;ol.PreRenderFunction&apos;, &apos;ol.ViewHint&apos;, &apos;ol.coordinate&apos;, &apos;ol.easing&apos;]);
        '''goog.addDependency(&apos;../../../ol/ol/array.js&apos;, [&apos;ol.array&apos;], [&apos;goog.array&apos;, &apos;goog.asserts&apos;]);
        '''goog.addDependency(&apos;../../../ol/ol/at [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property ol_deps() As String
            Get
                Return ResourceManager.GetString("ol_deps", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to // OpenLayers 3. See http://openlayers.org/
        '''// License: https://raw.githubusercontent.com/openlayers/ol3/master/LICENSE.md
        '''// Version: v3.4.0
        '''
        '''(function (root, factory) {
        '''  if (typeof define === &quot;function&quot; &amp;&amp; define.amd) {
        '''    define([], factory);
        '''  } else if (typeof exports === &quot;object&quot;) {
        '''    module.exports = factory();
        '''  } else {
        '''    root.ol = factory();
        '''  }
        '''}(this, function () {
        '''  var OPENLAYERS = {};
        '''  var l,aa=aa||{},ba=this;function m(b){return void 0!==b}function t(b,c,d){b=b.split(&quot;.&quot;);d=d||ba;b[0] [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property ol1() As String
            Get
                Return ResourceManager.GetString("ol1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property olstyle_icon__Direction_Marker() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("olstyle_icon__Direction_Marker", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property olstyle_icon__Green_Flat_Headed_Pin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("olstyle_icon__Green_Flat_Headed_Pin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property olstyle_icon__Green_Marker() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("olstyle_icon__Green_Marker", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property olstyle_icon_Black_Marker() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("olstyle_icon_Black_Marker", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property olstyle_icon_Blue_Dot() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("olstyle_icon_Blue_Dot", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property olstyle_icon_Green_Pin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("olstyle_icon_Green_Pin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property olstyle_icon_Orange_Pin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("olstyle_icon_Orange_Pin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property olstyle_icon_Straight_Blue_Pin() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("olstyle_icon_Straight_Blue_Pin", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property olstyle_line_Blue_Dashed() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("olstyle_line_Blue_Dashed", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property olstyle_line_Red_Line() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("olstyle_line_Red_Line", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property olstyle_marker_Blue_Point() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("olstyle_marker_Blue_Point", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property olstyle_marker_Red_Point() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("olstyle_marker_Red_Point", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property olstyle_polygon_Purple() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("olstyle_polygon_Purple", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property olstyle_polygon_Red() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("olstyle_polygon_Red", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized resource of type System.Drawing.Bitmap.
        '''</summary>
        Friend ReadOnly Property PencilTool_206() As System.Drawing.Bitmap
            Get
                Dim obj As Object = ResourceManager.GetObject("PencilTool_206", resourceCulture)
                Return CType(obj,System.Drawing.Bitmap)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to .
        '''</summary>
        Friend ReadOnly Property POPUPJS() As String
            Get
                Return ResourceManager.GetString("POPUPJS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!doctype html&gt;
        '''&lt;html lang=&quot;en&quot;&gt;
        '''  &lt;head&gt;
        '''  &lt;meta charset=&quot;utf-8&quot;&gt;
        '''  &lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;/&gt;
        '''
        '''    &lt;style&gt;
        '''      #map {
        '''        position: relative;
        '''      }
        '''      #popup {
        '''        padding-bottom: 0px;
        '''      }
        '''	  
        '''	  .map {
        '''	  
        '''		  height: 400px;
        '''		  width: 100%;
        '''			}
        '''			
        '''
        '''		#tags {
        '''		  display: none;
        '''		}
        '''
        '''		
        '''.clearfix {
        '''  *zoom: 1;
        '''}
        '''
        '''.clearfix:before,
        '''.clearfix:after {
        '''  display: table;
        '''  line-height: 0;
        '''  content: &quot;&quot;;
        '''}
        '''
        '''.clearfix:after {
        ''' [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property PopupJS1() As String
            Get
                Return ResourceManager.GetString("PopupJS1", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to  .
        '''</summary>
        Friend ReadOnly Property POPUPJSPREVEW() As String
            Get
                Return ResourceManager.GetString("POPUPJSPREVEW", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!DOCTYPE HTML&gt;
        '''&lt;HTML lang=&quot;en&quot;&gt;
        '''&lt;HEAD&gt;
        ''' 
        '''&lt;META charset=&quot;utf-8&quot;&gt; 
        '''&lt;META http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;&gt; 
        '''
        '''&lt;style&gt;
        '''/*!
        ''' * Bootstrap v3.2.0 (http://getbootstrap.com)
        ''' * Copyright 2011-2014 Twitter, Inc.
        ''' * Licensed under MIT (https://github.com/twbs/bootstrap/blob/master/LICENSE)
        ''' *//*! normalize.css v3.0.1 | MIT License | git.io/normalize */html{font-family:sans-serif;-webkit-text-size-adjust:100%;-ms-text-size-adjust:100%}body{margin:0}article,aside,details,figcaption,figure,foot [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property PopupJSPreview() As String
            Get
                Return ResourceManager.GetString("PopupJSPreview", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to !function(a){if(&quot;object&quot;==typeof exports)module.exports=a();else if(&quot;function&quot;==typeof define&amp;&amp;define.amd)define(a);else{var b;&quot;undefined&quot;!=typeof window?b=window:&quot;undefined&quot;!=typeof global?b=global:&quot;undefined&quot;!=typeof self&amp;&amp;(b=self),b.proj4=a()}}(function(){return function a(b,c,d){function e(g,h){if(!c[g]){if(!b[g]){var i=&quot;function&quot;==typeof require&amp;&amp;require;if(!h&amp;&amp;i)return i(g,!0);if(f)return f(g,!0);throw new Error(&quot;Cannot find module &apos;&quot;+g+&quot;&apos;&quot;)}var j=c[g]={exports:{}};b[g][0].call(j.exports,function(a){v [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property proj4() As String
            Get
                Return ResourceManager.GetString("proj4", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to &lt;!doctype html&gt;
        '''&lt;html lang=&quot;en&quot;  style=&apos;margin:0;padding:0;width: 100%; height: 100%;overflow:hidden;&apos;&gt;
        '''  &lt;head&gt;
        '''    &lt;meta charset=&quot;utf-8&quot;&gt;
        '''	&lt;meta http-equiv=&quot;X-UA-Compatible&quot; content=&quot;IE=edge&quot;/&gt;
        '''
        '''  &lt;/head&gt;
        '''  
        '''	&lt;body  style=&apos;margin:0;padding:0;width: 100%; height: 100%;&apos;&gt;
        '''		&lt;div id=&quot;map&quot; style=&quot;width: 100%; height: 100%;margin:0;padding:0;&quot;&gt;&lt;/div&gt;
        '''		&lt;script src=&quot;OLFILEPATHol.js&quot; type=&quot;text/javascript&quot;&gt;&lt;/script&gt;
        '''	
        '''&lt;script&gt;
        '''
        '''var PointFeature = new ol.Feature({
        '''  geometry: new ol.geom.Point([0,  [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property STYLEJS() As String
            Get
                Return ResourceManager.GetString("STYLEJS", resourceCulture)
            End Get
        End Property
        
        '''<summary>
        '''  Looks up a localized string similar to /*! URI.js v1.14.1 http://medialize.github.io/URI.js/ */
        '''/* build contains: IPv6.js, punycode.js, SecondLevelDomains.js, URI.js, URITemplate.js, jquery.URI.js, URI.fragmentURI.js */
        '''(function(c,h){&quot;object&quot;===typeof exports?module.exports=h():&quot;function&quot;===typeof define&amp;&amp;define.amd?define(h):c.IPv6=h(c)})(this,function(c){var h=c&amp;&amp;c.IPv6;return{best:function(c){c=c.toLowerCase().split(&quot;:&quot;);var m=c.length,b=8;&quot;&quot;===c[0]&amp;&amp;&quot;&quot;===c[1]&amp;&amp;&quot;&quot;===c[2]?(c.shift(),c.shift()):&quot;&quot;===c[0]&amp;&amp;&quot;&quot;===c[1]?c.shift():&quot;&quot;===c[m-1]&amp;&amp;&quot;&quot;== [rest of string was truncated]&quot;;.
        '''</summary>
        Friend ReadOnly Property URI() As String
            Get
                Return ResourceManager.GetString("URI", resourceCulture)
            End Get
        End Property
    End Module
End Namespace
